// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxenzvi8eo3Z7-bkAzOQXC2wTj_iAPJY',
    appId: '1:785145480437:web:ddc6d340f16f598f3d71bc',
    messagingSenderId: '785145480437',
    projectId: 'hvgl-app-2f7da',
    authDomain: 'hvgl-app-2f7da.firebaseapp.com',
    storageBucket: 'hvgl-app-2f7da.firebasestorage.app',
    measurementId: 'G-HE384ZXH21',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwTs5bKBrekYHWfNPNErfRm6wfusfVvqc',
    appId: '1:575957738296:ios:b7d91e9491edb4e62917cd',
    messagingSenderId: '575957738296',
    projectId: 'hvnb-706d5',
    storageBucket: 'hvnb-706d5.firebasestorage.app',
    iosBundleId: 'vn.hvgl.noibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwTs5bKBrekYHWfNPNErfRm6wfusfVvqc',
    appId: '1:575957738296:ios:b7d91e9491edb4e62917cd',
    messagingSenderId: '575957738296',
    projectId: 'hvnb-706d5',
    storageBucket: 'hvnb-706d5.firebasestorage.app',
    iosBundleId: 'vn.hvgl.noibo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgxenzvi8eo3Z7-bkAzOQXC2wTj_iAPJY',
    appId: '1:785145480437:web:95f233b81b57aa353d71bc',
    messagingSenderId: '785145480437',
    projectId: 'hvgl-app-2f7da',
    authDomain: 'hvgl-app-2f7da.firebaseapp.com',
    storageBucket: 'hvgl-app-2f7da.firebasestorage.app',
    measurementId: 'G-JTQP2R0GCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQbsRvCIIX2HvKtT0c1h9bg8VO6mTBASc',
    appId: '1:575957738296:android:e4842d243bd4eaaa2917cd',
    messagingSenderId: '575957738296',
    projectId: 'hvnb-706d5',
    storageBucket: 'hvnb-706d5.firebasestorage.app',
  );

}